davidmarkclements/0x

.gitignore
examples/simple/simple.js

Two minor nits:
* it was a little easier to have (tracing unrelated) testing with a simpler example. This commit adds one.
* also IDE experience was a little nicer when output was excluded
I can separate those of course, but they seemed too small at the time.

tooling: adds simpler example, .gitignore: exclude output

---

examples/simple/index.js
index.js
readme.md

Addresses Revert #17 of #15. 
Note: there might be unrelated race conditions and an unrelated bug on linux, when called with binary or plain `node` binary argument.

feature: adds autoexit option. Default: do autoexit after script

---

changelog.md
cli-schema.json
cmd.js
index.js
lib/stack-convert.js
lib/util.js
readme.md
usage.txt

+@mafintosh 
The `--phase` option does away with default delay of 300ms 
By default it strips away all startup stacks, everything in the first tick (`--phase` is 2)
If `--phase` is 1, then any stacks from Module.runMain (e.g. execution from the entry point file) are included, these still tend to dominate because the applications module tree is loaded from this point but in some cases (say a CLI tool) this would be useful
`--phase` 0 includes everything in the bootstrap process, including all NativeModule stacks etc. 
Also include a programmatic API option `phase` (as the flag) and `mapFrames` which allows for a custom mapping function.

phase option, closes #90

---

changelog.md
cli-schema.json
cmd.js
lib/prof-log-convert.js
lib/stack-convert.js
lib/util.js
package.json
platform/linux.js
platform/sun.js
readme.md
usage.txt

comments welcome
@mafintosh @bridgeAR @lucamaraschi @mcollina

--prof-viz extra flame graph based on v8 prof data 

---

index.js
package.json

makes `$PORT` work everywhere (before windows users had to do `%PORT%` and unix'ers `$PORT`. We still set the env so `%PORT%` is still supported if you really want to

use env-string to inline envs for better xplatform support

---

lib/trace-stacks-to-ticks.js

Problem:
If the file with trace stacks is larger than the maximum string length,
then traceStacksToTicks chokes on a call to toString.
Solution:
Split buffer on newlines via repeated indexOf rather than via
buf.toString.split('\n')
Test:
I ran assert.deepEqual to compare the stacks generated by the
old and new approaches. It said they were equivalent.
Fixes: #120

Safely parse large trace stacks files

---

visualizer/cmp/graph.js
visualizer/cmp/key.js
visualizer/cmp/search.js
visualizer/cmp/zoom.js

- Fixes the height of the graph in FF
For some reason `height: calc(100% - 66px)` does something totally
different than `height: 100%`, but with `100vh` the behaviour is the
same either way. This seems like a FF CSS bug maybe…
- Use floating + margins instead of absolute positions for top bar
controls
Default button and input sizes are different across browsers and OSes,
by using floats + margins the positioning adapts to sizes instead of
having things drawn on top of each other.
Before
After

Style fixes

---

visualizer/actions.js

- Allow zooming in beyond 100% size
- When toggling one of the Optimized/unoptimized buttons, disable the other
May be best to wait for the new d3-fg to be on npm but these changes are not harmful before then either.

Updates for new d3-fg

---

lib/preload/detect-port.js
platform/v8.js

Using childProcess.kill on windows have a ton of issues as its equi of kill -9 on unix. this changes it to use a 'soft signal' instead

fix signalling on windows

---

package.json
visualizer/index.js

When I resize the browser window in `flamegraph.html`, I get the following error in console.
```
Uncaught TypeError: Cannot read property 'setAttribute' of null
at window.addEventListener.debounce (flamegraph.html:11197)
at later (flamegraph.html:9405)
```
The error happens because the code tries to resize an `<svg>` element while `d3-fg` doesn't use `<svg>` anymore.
This PR removes the line causing the error. Even without the line, the line above resizes the chart properly.

Fix error on resize

---

lib/render.js
package.json

Fixes #147
Removing standalone bundles of `hsl-to-rgb-for-reals` and `d3-fg` because the modules are already included in the `../visualizer` bundle.
As a result, the size of `flamegraph.html` from `examples/api.js` decreased roughly from 828 KB to 559 KB.

Remove duplicated JS from flamegraph.html

---

lib/preload/no-cluster.js
platform/v8.js

0x doesn't support multi processes.
I used the 'fork' event because it's easier than intercepting `require`
and this way it allows requiring but not using `cluster`.
If the subprocess does `try { cluster.fork() }` this won't crash, but
that's probably fine? Same if the subprocess has an 'uncaughtException'
handler.
Ex:
```
➜  ./cmd.js cluster.js
🔥  Profiling/home/goto-bus-stop/Code/nearform/0x/lib/preload/no-cluster.js:4
throw new Error('0x does not support clustering.')
^
Error: 0x does not support clustering.
at EventEmitter.cluster.on (/home/goto-bus-stop/Code/nearform/0x/lib/preload/no-cluster.js:4:9)
at EventEmitter.emit (events.js:182:13)
at emitForkNT (internal/cluster/master.js:226:11)
at process._tickCallback (internal/process/next_tick.js:63:19)
at Function.Module.runMain …
```

Throw error if a cluster subprocess is forked

---

examples/rest-api/package.json
package.json
platform/v8.js

This fixes an issue where, if the subprocess was stuck on a sync operation, pressing Ctrl+C would generate a flame graph and exit 0x, but the subprocess would keep spinning on in the background.
I used:
```js
// loop.js
while (true);
```
```bash
./cmd.js loop.js
```
Previously, doing Ctrl+C would generate the flame graph, and then 0x would keep running afterward because the subprocess hadn't ended. Sending another Ctrl+C would terminate 0x, as it no longer has a SIGINT handler, but the subprocess would keep running.
With this patch, we catch two SIGINTs—the first uses the `stdio[5].destroy()` soft-close mechanism like before, and the second sends a SIGTERM to the subprocess. 0x suggests sending a second Ctrl+C if soft-closing takes a very long time.
As a last-resort measure, a SIGTERM is …

Send SIGTERM to subprocess on second Ctrl+C

---

lib/preload/redir-stdout.js

No matter how you write to stdout, this should catch it!
The `defineProperty` call uses the same options as the default `process.stdout`.

Change process.stdout.write switcharoo to a full net.Socket instance

---

visualizer/actions.js
visualizer/index.js
visualizer/state.js

A flame graph made with this version is viewable at https://upload.clinicjs.org/public/509680025b4cc97cec5a7e2eaacdb90c10c5585ba70b7bb8656bc3985db468c1/8353.clinic-flame.html (see below for direct stack frame link examples)
This patch stores the current focused node in the URL hash, so you can
link to a specific stack. It does that by assigning each node an ID on
load. It's a counter that does a preorder traversal, this is a safe way
to do it because the data that is used is static, stack frame 352 will
be the same regardless of who opens the file.
It also implements the back/forward buttons using the `pushState()` API.
Only the merged/unmerged setting, the type visibility settings (c++, v8, etc)
and the focused node ID are stored, because those must be known in order
to show the correct …

Direct stack frame #-links + history

---

.gitignore
lib/ticks-to-tree.js
platform/linux.js
platform/sun.js
platform/v8.js
readme.md
usage.txt
visualizer/index.js

Fixes: #144
Tested in Node.js 10 and 8
Before:
After:

Filter init

---

lib/util.js
package.json

This is to allow 0x to put its output in a subdirectory like, for example:
```
./12345.clinic-flame/12345.clinic-flame-0x-data
```
...so that 3rd party tools that use 0x as an API can more neatly separate 0x's output from their own outputs.
This adds a dependency, [`make-dir`](https://www.npmjs.com/package/make-dir), to handle recursive directory creation. It's actively maintained and appears more robust and simple than the alternatives.

Allow 0x to create output in a subfolder of a new folder

---

index.js
lib/v8-log-to-ticks.js
platform/linux.js
platform/sun.js
platform/v8.js

This was the case when 0x was used in a programatic way.

Do not require pathToNodeBinary to be set

---

lib/ticks-to-tree.js

This improves the init detection in two ways: it should stop detecting some native frames as init and it should detect esm modules properly.
I was not able to reproduce the native frames but it should still work properly.
At the moment the esm detection adds the next tick file to the init phase as well (`internal/process/next_tick.js`) and I am somewhat on the edge of having it in INIT or not. Opinions?

Improve init

---

index.js

When running the visulization step the binary path was not passed
through properly. This is now fixed.
Fixes: https://github.com/nearform/node-clinic/issues/62

Fix binary path not found

---

index.js
platform/v8.js

Depending on when the error occurs, it's possible for 0x's collect branch using the V8 platform to leave V8 isolate log files lying around in the main working directory after exit. This causes problems such as filling up CI servers of tools that use 0x and have tests for their own handlers for such errors.
To replicate, try running this from the command line. An isolate log file will be created and will persist after completion:
```
0x -- node -e 'setTimeout(() => { fail() }, 1000)'
```
This PR adds a cleanup error handler that deletes any such log if there is an error in the V8 process. Run the above command in this branch while watching the working directory and you should be able to see the isolate log file be created, then deleted after a second when the error is hit.

Don't leave isolate log debris if command execution hits error

---

lib/random-require.js
lib/ticks-to-tree.js

Before:
After:
This also moves the main filter logic into the executed function.
This seemed cleaner instead of having to do this in the receiving
part.
Fixes: https://github.com/davidmarkclements/0x/issues/186

Filter next tick

---

lib/ticks-to-tree.js
package.json

Fixes https://github.com/davidmarkclements/0x/issues/190

Escape __dirname before generating regexp

---

platform/linux.js
platform/sun.js
platform/v8.js

Related to issue #198 and nearform/node-clinic#73
Do not throw on client application termination.
Only report error and continue processing the traces.
Adjusted handler to only report error.

do not abort on process exit code

---

platform/v8.js

This fixes an issue with log output lines like these (observed in Node 10.3 on Arch Linux):
```
INLINE (pp.expect) id{43--- FUNCTION SOURCE (/home/goto-bus-stop/Code/goto-bus-stop/dash-ast/node_modules/acorn/dist/acorn.js:isKeyword) id{45,-1} start{27997} ---
INLINE (pp$8.curContext) id{54,3} AS 3--- FUNCTION SOURCE (/home/goto-bus-stop/Code/goto-bus-stop/dash-ast/node_modules/acorn/dist/acorn.js:pp$5.enterLexicalScope) id{56,-1} start{108848} ---
INLINE (has) id{73,2} AS 2 AT <--- FUNCTION SOURCE (/home/goto-bus-stop/Code/goto-bus-stop/dash-ast/bench/index.js:enter) id{75,-1} start{1141} ---
```
Previously, we loosened the FUNCTION SOURCE check so we would detect it
starting in the middle of another function. This issue occurs when a
FUNCTION SOURCE block starts in the middle of an …

Fix more opt log output artifacts

---

docs/api.md
index.js
platform/linux.js
platform/sun.js
platform/v8.js
schema.json

Adds a callback that's called ASAP when the profiled process exits. This allows showing the "Analysing data" message early in Flame.

Add onProcessExit option.

---

.travis.yml
lib/v8-log-to-ticks.js
package.json
test/fixture/do-eval.js
test/fixture/μИاκهよΞ/unicode-in-path.js
test/util/classify-frames.js
test/util/ensure-eval-safe.js
test/util/type-edge-cases.js
test/util/type-simple-cases.js
test/v8-names-static.test.js
test/v8-types-generated.test.js
test/v8-types-static.test.js
visualizer/cmp/graph.js

This does quite a few things:
- Brings test coverage up, from almost nothing to >~50% on Node 11 (note that `tap --cov` breaks 0x on Node 8):
```
---------------------------|----------|----------|----------|----------|-------------------|
File                       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------------|----------|----------|----------|----------|-------------------|
All files                  |    57.48 |    47.77 |    57.01 |    58.18 |                   |
```
- Adds unit and integration tests for backend log processing and frame naming
- Adds unit and integration tests for frontend type classification used by the filter buttons
- Fixes things (all of which are covered in the tests):
- Fixes …

Add tests for V8 log and UI classification, fix some Windows bugs and edge cases

---

lib/ticks-to-tree.js

0x fails in lib/ticks-to-tree.js if it is running inside a Tap test with coverage enabled on Node 8, which causes lib/random-require.js to return an empty string. There are probably other similar scenarios too, where something observing child processes interferes.
The point it fails doesn't give much of a clue about what happened - it's an assert in a file two removed from where the problem actually occurs, and the problem itself happens in random-require.js which is hard to debug because it uses console.log output to communicate with the parent process that calls it. Then quite a leap of logic is needed to link this to the actual cause (e.g. Tap coverage).
So it's helpful to give users and contributors an informative error message at this point.

Add informative error message for known point of failure (observers like Tap coverage on Node 8)

---

lib/preload/redir-stdout.js

This breaks running 0x with Workers, because the internal stdio
implementation for Workers currently relies on `process.stdout`
being the originally provided object.

Skip redirecting stdout for Worker threads

---

index.js
lib/util.js
platform/v8.js

The isolate log filename from V8 now includes the pid by default, so combined with our
custom `--logfile` pattern it adds the pid twice. This updates the
regexes to account for an optional duplicate pid.

Update isolate log regexes for V8 7.3

---

lib/ticks-to-tree.js

I guess the new --experimental-modules implementation changed this
behaviour. Doing `node --experimental-modules ./no-extension` doesn't
do extension probing now, so we have to spell out the `.js`.

Fix init stack regex setup with latest Node master

---

lib/cpu-profile-to-tree.js
lib/render.js
visualizer/state.js

fs.promises is available in Node 10+ only. By using promisify(fs.readFile) instead we stay compatible with Node 8.
Fixes https://github.com/nearform/node-clinic/issues/156
Fixes https://github.com/nearform/node-clinic/issues/157

Fix Node 8 compatibility

---

lib/ticks-to-tree.js
visualizer/cmp/graph.js
visualizer/cmp/type-filters.js
visualizer/state.js

wasm stack frames are outputted (output? put out?) basically with only their name, and no location data. I tried finding other differences between wasm and JS frames but there don't seem to be any.
This PR marks JS frames that don't have a source location as WASM frames. I'm not 100% sure that is right, but it should be close—Clinic Flame would've crashed in the past on JS frames without a filename and it has seen quite a few projects by now. Do we know if anything else may cause missing location data?
The [WASM] tag allows clinic flame to handle the wasm stack frames specially (eg. by setting a default filename or labelling them differently).
0x already "worked" without this, but wasm frames were categorised as V8 frames, which is quite inaccurate. This categorises wasm frames as …

Flag likely wasm stack frames

---

lib/v8-log-to-ticks.js

In the following simple code example, the `pbkdf2Sync` is blocking the event loop and is taking >90% of total ticks.
```js
const express = require('express')
const crypto = require('crypto')
const app = express()
app.get('/', async (req, res) => {
const salt = crypto.randomBytes(128).toString('base64')
crypto.pbkdf2Sync('test', salt, 10000, 512, 'sha512')
res.status(200).send('hello world')
})
app.listen(3000)
```
But this function is not marked as "hot" in the flame chart and only visible as a small block.
Running Node.js with the `--prof-process` flag on the isolate-log that was generated through 0x, does show the issue.
```txt
[C++]:
ticks  total  nonlib   name
8459   95.2%   95.4%  T node::crypto::PBKDF2(v8::FunctionCallbackInfo<v8::Value> const&)
165    1.9%    1.9%  t …
```

fix: Missing ticks data

---

platform/v8.js
test/basic.test.js

When using the API, and specifying a different `workingDir`, the process crashes with the following error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`
It was originally reported in issue #228 and and fixed in PR #229 but a test is still missing to get it merged.
This PR applies the same fix, and adds a test to validate the error does not occur anymore.

fix: error msg on workingdir

---

platform/v8.js

The bug prevented a file match on a system in which %p or std::ostream&<< doesn't prefix the address with 0x, as on z/OS.
Note the updated regex now also matches the 0x part in index.js visualize().

fix regex bug of optional 0x prefix

---

cmd.js
docs/api.md
index.js
lib/v8-log-to-ticks.js
platform/v8.js
readme.md
schema.json
usage.txt

Original PR is here: https://github.com/davidmarkclements/0x/pull/222
> For 0x the delay won't hold up the process but rather filter the data depending on the delay value passed in. Open to feedback and further changes/suggestions.
This as the effect of only rendering flamegraphs with data after the delay ends. 
This solves some use cases of https://github.com/davidmarkclements/0x/issues/129. 
My own use case is not wanting to see output from the initial boot of my app (different problem, distracting!) but rather focus on what happens when requests are received. 
I am aware the code is untested, keen for some input on where to start with adding tests as the critical affected code in  lib/v8-log-to-ticks.js appears to be as yet untested as far as I can tell.

Collect timeout feature

---

lib/ticks-to-tree.js
lib/trace-stacks-to-ticks.js
platform/linux.js

Address: #242 
This PR also adds support to categorization through perf stack traces.

linux: fixes perf profiling stacktraces

---

lib/preload/soft-exit.js
package.json
platform/linux.js
platform/v8.js
readme.md

When I was using  docker-compose I could not generate the flame-graph because the default signal sent by docker-compose is SIGTERM, there are ways to send SIGINT instead of SIGTERM but that adds more complexity to the docker-compose file, and since SIGTERM is not a force exit signal I think that it should be handled the same way that SIGINT is.

Adding the SIGTERM to soft exit

---

lib/ticks-to-tree.js

I'm still looking if there is something missing because looks like the call stack are not completely correct. 
By the way, I'm running this fork: https://github.com/RafaelGSS/slow-rest-api
```console
node ../node-clinic/bin.js flame --on-port='npm run test' -- node index.js
```
and I'm getting the graph attached
Look that `payload` function is side by side of `a`/`b`/`c`/ function which is its caller
Does that is acceptable? @mcollina
[204430.clinic-flame.zip](https://github.com/davidmarkclements/0x/files/7945683/204430.clinic-flame.zip)

fix: add support to inlined functions + sparkplug on v16+

---

index.js

In v8-log-to-ticks.js:152
```
const delayMs = options.collectDelay * 1000
...
// Compare ticks to first for collectDelay
if (tick.tm > (firstTick[0] + delayMs)) {
ticks.push(stack.reverse())
}
```
But without this change, `collectDelay` is `NaN` so `firstTick[0] + NaN` ends up `NaN`, which always returns false when compared to a number, so this never resolves to true, and no ticks get added.

fix: collect-only to render-only flow

---

lib/cpu-profile-to-tree.js
test/cpu-profile-to-tree.test.js

This pr refactors out the code that does the filtering of parenthesized nodes like `(idle)` and `(garbage collector)` in `cpu-profile-to-tree.js`, as well as doing some related cleanup and testing.
As a side note, it appears that `(program)` [refers to V8 infrastructure code](https://github.com/nodejs/node/blob/61c7103ed06e5364eddae4586f90ee97531e14a6/deps/v8/src/profiler/symbolizer.cc#L28-L38) and that `(idle)`, `(garbage collector)` and `(program)` are guaranteed [not to have any children](https://github.com/nodejs/node/blob/61c7103ed06e5364eddae4586f90ee97531e14a6/deps/v8/src/profiler/symbolizer.cc#L172-L181) but this does assume that I'm reading the code correctly and that conclusions made on Node's V8 code is generalizable to other V8 implementations.

cpu-profile-to-tree: Refactor out the filtering of parenthesized nodes

---

readme.md
usage.txt

This pr updates the documentation for the `--visualize-cpu-profile` flag in `readme.md` and `usage.txt`. It also removes trailing spaces from `usage.txt`.

Update `--visualize-cpu-profile` docs

---

.github/workflows/ci.yml
test/v8-types-generated.test.js

Updated regexp to match output of 18 node too.
Node 12.x lifecycle is ended. So we can probably delete it from CI.

Fix test for 18 node and add it to CI

---

package.json
platform/v8.js

It's impossible to use 0x with volumes mounted on different file systems.
```
Error: 
EXDEV: cross-device link not permitted, rename '/dir1/isolate-0x2f2a329ae330-418-418-v8.log' -> '/dir2/isolate-0x2f2a329ae330-418-418-v8.log'
```
The reason of such behavior is `fs.rename`. So I added `fs-extra` and use `move` instead.
P.S. Also, there was infinity loop in `renameSafe`. This is because of `i++` :see_no_evil: 
Probably fix https://github.com/davidmarkclements/0x/issues/241

Fix: EXDEV: cross-device link not permitted

---

docs/kernel-tracing.md
platform/linux.js

Reference: https://github.com/clinicjs/node-clinic-flame/issues/171.
I haven't found an valid approach to pipe between a non-nodejs process. To summarize the problem:
When no kernel-tracing:
- Root process spawn a new Node.js process
- The communication happens using a new `fd` (created using the `stdio` option).
When kernel-tracing:
- Root process spawn a non-nodejs process that spawn a nodejs process (nodejs -> linux_perf -> nodejs)
- So, the communication between the root process and nodejs doesn't work.
The best option so far is improving the UX by throwing an error when both options are used together, instead quitting silently

update: add on-port check when kernel-tracing

---

lib/trace-stacks-to-ticks.js

Fixes: https://github.com/clinicjs/node-clinic/issues/380

update: support Node.js v19 Kernel Traces

---

lib/preload/soft-exit.js

0x didn't work for me when using node v20 because calling process.exit with invalid arguments will throw an exception

fix: node v20 complains of invalid arguments
