davidmarkclements/0x

- index.js
- package.json
- readme.md
- usage.txt
- Fixing a problem with browserify shims if the traced project
uses browserify its self
- Adding timestamp to profile dir to avoid collision (ie: in docker
containers)
- Adding Docker trick in readme
> Fixing a couple of minor problems

- gen.js
This adds scroll to bottom on content load. It's sort of a single and simple visual enhancement.
Note: there are some whitespace errors, my editor corrects automatically. Hope including those is no problem.
> feature: scroll to buttom on content load

- cmd.js
- index.js
Adds actual support for external / custom binaries.
See discussion on #10
re-opens #10, closes #10
> feature: adds support for ext. node binaries like ../node/node

- examples/simple/index.js
- index.js
- readme.md
@davidmarkclements maybe this would be interesting for you. Don't know what your plan for this was, but I like the notion of autoexiting, after the script has run. It will however wind down the rest of the app logic.
> feature: adds autoexit option. Default: do autoexit after script

- examples/simple/index.js
- index.js
- readme.md
Reverts davidmarkclements/0x#15
@eljefedelrodeodeljefe just rolling this back until we have the same behaviour on linux (unless that's already the behaviour, in which case need to verify)
> Revert "feature: adds autoexit option. Default: do autoexit after script"

- index.js
**Problem**
This fixes the sypmtoms of issue #41 on Fedora 24 (and potential other
distros).
The `perf script` command is being executed too soon before the `perf
record` command finishes writing its contents to the tmp perf file.
As a result, the `perf script` command fails with an error.
**Solution**
Only execute the `perf script` command when the `perf record` process fires an `exit` event 
**Before**
```
$ DEBUG=0x,0x:stack-convert 0x --trace-info index.js
Profiling^C[ perf record: Woken up 8 times to write data ]
0x Caught SIGINT, generating flamegraph +0ms
Caught SIGINT, generating flamegraph WARNING: The /tmp/perf-3ns4rp.data
file's data size field is 0 which is unexpected.
Was the 'perf record' command properly terminated?
0x begin rendering +48ms
0x:stack-convert serializing …
```
> Fix for empty flamegraph on linux

- command.js
> bug: use path.join() for command-usage

- readme.md
as stated :)
This is the issue:
> Better readme.md on npm

- index.js
- readme.md
> Detect location of profile_1ms.d as .bin resident

- readme.md
> Add documentation about memory issues

- index.js
@davidmarkclements as titled, highly useful!!!
@jasnell, this solves our problem for generating flamegraphs for http2 on Mac.
> Support custom node core builds

- cmd.js
- index.js
- usage.txt
> feat: support custom output directory via -o / --output-dir

- readme.md
> Include troubleshooting remedy for empty stacks

- index.js
Also, fixed max attempts at expecting prof process dying.
Should fix #66
> Killing the profiling process if it stubbornly refuses to die

- flamer.js
> Hide BytecodeHandler within V8 tab

- index.js
This also works on Node 8.3.0-rc.0. Fantastic.
> Fix support for Linux (Ubuntu 17.04)

- cmd.js
- flamer.js
- gen.js
- index.js
- package.json
- usage.txt
and B&W (to see the contrast)
I have also fixed some layout issues.
> More contrasted colors

- cmd.js
- index.js
I didn't make the corresponding linux change because I'm not currently set up to test it.  It would be the same simple concatenation.
Also added restify dependency
https://github.com/davidmarkclements/0x/issues/70
> pass command line arguments through to spawned process

- changelog.md
- cli-schema.json
- lib/util.js
- readme.md
> output dir interpolation, closes #88

- changelog.md
- cli-schema.json
- cmd.js
- index.js
- lib/util.js
- platform/index.js
- platform/v8.js
- readme.md
- usage.txt
this is really providing the basis for v4
cc @jasnell @mafintosh @lucamaraschi
> --prof-only

- readme.md
> formatting

- platform/v8.js
> Fixed windows resource busy bug

- index.js
the regex stopped working for me on windows with node 10.6+
> fix regex on windows

- visualizer/index.js
Follow up on https://github.com/davidmarkclements/0x/pull/143
Before:
After:
> Add top offset to prevent top bar from cropping the top stack

- platform/v8.js
Reading v8 output from the stdout stream of a child process is sometimes
unreliable, chunks may be missing. The next `FUNCTION SOURCE` can be in
the middle of a previous `FUNCTION SOURCE`, cutting it off. The impact
can be alleviated slightly by accepting `FUNCTION SOURCE` identifiers
that occur in the middle of a line. It's not 100% accurate, because the
missing chunks may contain other `FUNCTION SOURCE` blocks, so we can
still be missing out on stuff. But, at least we don't dump function
source code to the shell anymore.
When this happens, the previous FUNCTION SOURCE block will not have been
closed by an END line, but END lines only set
`stdoutIsPrintOptSourceOutput` to false, and FUNCTION SOURCE lines set
it to true, so we don't have to do anything there.
I tightened the FUNCTION …
> Accept FUNCTION SOURCE identifiers mid-line

- visualizer/cmp/graph.js
Now all v8 stacks are detected properly.
Fixes: #142
> Improve v8 detection

- visualizer/cmp/graph.js
Some calls were not properly detected before. The heuristic is now
improved.
> Move more cpp functions to v8

- cmd.js
- index.js
- lib/v8-log-to-ticks.js
- platform/v8.js
- visualizer/html.js
So far the child process spawned to vizualize the data could be a
different one than the one used to run 0x. Now it's always the same
and there should be no mismatch left.
Fixes: #119
> Make sure the same Node.js executable is used

- cmd.js
- index.js
- lib/render.js
- lib/ticks-to-tree.js
Slow rest api:
Node master with init:
Node master without init:
Node 10.9 without init:
Node 8.12 without init:
Some util inspect code:
Node master with init:
Node master without:
Node 10.9 with init:
Node 10.9 without init:
Node 8.12 without init:
> Remove load phase

- lib/v8-log-to-ticks.js
Should fix https://github.com/davidmarkclements/0x/issues/192 until we can fix it in V8
> Workaround for v8 tick processor bug

- .github/workflows/stale.yml
I have seen that some issues and PR are out-of-date in order to keep it maintainable this action might be useful.
> chore: add stale workflow

- lib/preload/redir-stdout.js
- test/fixture/log-stdout-fd.js
- test/redir-stdout.test.js
Address: https://github.com/clinicjs/node-clinic/issues/337
It's still WIP because I'm looking to other approaches, the current one looks quite hacky to me.
> fix: override process.stdout.fd

- test/cpu-profile-to-tree.test.js
This pr adds a test for #256, which currently has no tests.
> Add test for #256 (`--cpu-prof` `.cpuprofile`)

- visualizer/html.js
Enabling the dark mode if it is configured at the OS level.
This is how it will look like
> Set black background on dark theme

- platform/v8.js
- test/fixture/stdin.js
- test/read-stdin.test.js
> Allow stdin to work while profiling

- cmd.js
- schema.json
- test/basic.test.js
- usage.txt
> Allow configuring the cwd of the profiler via cli flags
